from flask import Flask, render_template, request, redirect, url_for, flash
import os
import json

from main import ProductivityAnalyzer

app = Flask(__name__)
app.secret_key = 'analysis_secret_key_2025'

UPLOAD_FOLDER = 'uploads'
OUTPUT_FOLDER = 'output'
PLOTS_FOLDER = 'static/plots'

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)
os.makedirs(PLOTS_FOLDER, exist_ok=True)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze():
    if 'data_file' not in request.files:
        flash('No file selected.')
        return redirect(url_for('index'))

    file = request.files['data_file']
    if file.filename == '':
        flash('No file selected.')
        return redirect(url_for('index'))

    if not file.filename.lower().endswith('.csv'):
        flash('Only CSV files are allowed.')
        return redirect(url_for('index'))

    filepath = os.path.join(UPLOAD_FOLDER, 'analysis_data.csv')
    file.save(filepath)

    try:
        analyzer = ProductivityAnalyzer(
            data_file=filepath,
            output_dir=OUTPUT_FOLDER
        )
        results = analyzer.run_complete_analysis()

        if not results:
            flash("Analysis failed. Check logs.")
            return redirect(url_for('index'))

        # List of all plot files generated by the analyzer
        plot_files = [
            'descriptive_analysis_1.png',
            'descriptive_analysis_2.png',
            'descriptive_analysis_3.png',
            'descriptive_analysis_4.png',
            'pca_analysis_1.png',
            'pca_analysis_2.png',
            'simple_regression_analysis_1.png',
            'simple_regression_analysis_2.png',
            'simple_regression_analysis_3.png',
            'simple_regression_analysis_4.png',
            'multiple_regression_analysis_1.png',
            'multiple_regression_analysis_2.png',
            'multiple_regression_analysis_3.png',
            'multiple_regression_analysis_4.png',
        ]

        # Pass the plot filenames to the template for display
        return render_template('results.html', results=results, plot_files=plot_files)

    except Exception as e:
        flash(f"Error: {str(e)}")
        return redirect(url_for('index'))

if __name__ == '__main__':
    app.run(debug=True)